apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: pewtils-runner
  namespace: github-runners

spec:
  replicas: 1
  template:
    spec:
      repository: pewresearch/pewtils_dev
      image: 458280294434.dkr.ecr.us-east-1.amazonaws.com/labs-actions-runner@sha256:c55e5a910037c801088f9703f6d3382e56573af327c0a5517d468d033f16cd05
      imagePullPolicy: Always
      serviceAccountName: labs-runner
      labels:
        - labs-runner
      dockerEnabled: false
      dockerd`ontainerResources:
        limits:
          cpu: "4.0"
          memory: "8Gi"

        requests:
          cpu: "1.0"
          memory: "2Gi"

      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_SECRET_ACCESS_KEY

    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
