apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: pewtils-dev-runner
  namespace: github-runners

spec:
  replicas: 1
  template:
    spec:
      repository: pewresearch/pewtils_dev
      image: 458280294434.dkr.ecr.us-east-1.amazonaws.com/labs-actions-runner@sha256:8641c1ca4013c3eae64c6d767b30ca833df913c0b731d7ffead98ebed6171441
      imagePullPolicy: Always
      serviceAccountName: labs-runner
      labels:
        - pewtils-runner
      dockerEnabled: false
      dockerdContainerResources:
        limits:
          cpu: "4.0"
          memory: "8Gi"

        requests:
          cpu: "100m"
          memory: "2Gi"

      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_SECRET_ACCESS_KEY

    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

---

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: pewtils-runner
  namespace: github-runners

spec:
  replicas: 1
  template:
    spec:
      repository: pewresearch/pewtils
      image: 458280294434.dkr.ecr.us-east-1.amazonaws.com/labs-actions-runner@sha256:8641c1ca4013c3eae64c6d767b30ca833df913c0b731d7ffead98ebed6171441
      imagePullPolicy: Always
      serviceAccountName: labs-runner
      labels:
        - pewtils-runner
      dockerEnabled: false
      dockerdContainerResources:
        limits:
          cpu: "4.0"
          memory: "8Gi"

        requests:
          cpu: "100m"
          memory: "2Gi"

    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
