name: unit-tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  unit-tests:
    name: unit-tests
    runs-on: labs-runner

    steps:
      - uses: actions/checkout@v2

#       - name: install os dependencies
#         run: |
#           set -ex
#           apt-get -qy update
#           apt-get -qy --no-install-recommends install zip

      - name: Install python dependencies
        run: |
          pip3 install flake8
          pip3 install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          python3 -m unittest tests
