name: unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: unit-tests
    runs-on: labs-runner

    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: |
          pip3 install flake8
          pip3 install -r requirements.txt

      - name: Lint with flake8
        run: |
          make python_lint

      - name: Run unit tests
        run: |
          make python_test
